[project]
name = "cerebella"
version = "0.1.10"
description = "this is how coding with AI should feel"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
cerebella = "main:main"
